# -*- coding: utf-8 -*-

questions_data = [
    # A: 仕事のストレス要因 (17問)
    {"id": "A1", "text": "A1. 非常にたくさんの仕事をしなければならない", "category": "A", "reverse": False},
    {"id": "A2", "text": "A2. 時間内に仕事が処理しきれない", "category": "A", "reverse": False},
    {"id": "A3", "text": "A3. 一生懸命働かなければならない", "category": "A", "reverse": False},
    {"id": "A4", "text": "A4. かなり注意を集中する必要がある", "category": "A", "reverse": False},
    {"id": "A5", "text": "A5. 高度の知識や技術が必要なむずかしい仕事だ", "category": "A", "reverse": False},
    {"id": "A6", "text": "A6. 勤務時間中はいつも仕事のことを考えていなければならない", "category": "A", "reverse": False},
    {"id": "A7", "text": "A7. からだを大変よく使う仕事だ", "category": "A", "reverse": False},
    {"id": "A8", "text": "A8. 自分のペースで仕事ができる", "category": "A", "reverse": True},
    {"id": "A9", "text": "A9. 自分で仕事の順番・やり方を決めることができる", "category": "A", "reverse": True},
    {"id": "A10", "text": "A10. 職場の仕事の方針に自分の意見を反映できる", "category": "A", "reverse": True},
    {"id": "A11", "text": "A11. 自分の技能や知識を仕事で使うことが少ない", "category": "A", "reverse": False},
    {"id": "A12", "text": "A12. 私の部署内で意見のくい違いがある", "category": "A", "reverse": False},
    {"id": "A13", "text": "A13. 私の部署と他の部署とはうまが合わない", "category": "A", "reverse": False},
    {"id": "A14", "text": "A14. 私の職場の雰囲気は友好的である", "category": "A", "reverse": True},
    {"id": "A15", "text": "A15. 私の職場の作業環境（騒音、照明、温度、換気など）はよくない", "category": "A", "reverse": False},
    {"id": "A16", "text": "A16. 仕事の内容は自分にあっている", "category": "A", "reverse": True},
    {"id": "A17", "text": "A17. 働きがいのある仕事だ", "category": "A", "reverse": True},

    # B: 心身のストレス反応 (29問)
    {"id": "B1", "text": "B1. 活気がわいてくる", "category": "B", "reverse": True},
    {"id": "B2", "text": "B2. 元気がいっぱいだ", "category": "B", "reverse": True},
    {"id": "B3", "text": "B3. 生き生きする", "category": "B", "reverse": True},
    {"id": "B4", "text": "B4. 怒りを感じる", "category": "B", "reverse": False},
    {"id": "B5", "text": "B5. 内心腹立たしい", "category": "B", "reverse": False},
    {"id": "B6", "text": "B6. イライラしている", "category": "B", "reverse": False},
    {"id": "B7", "text": "B7. ひどく疲れた", "category": "B", "reverse": False},
    {"id": "B8", "text": "B8. へとへとだ", "category": "B", "reverse": False},
    {"id": "B9", "text": "B9. だるい", "category": "B", "reverse": False},
    {"id": "B10", "text": "B10. 気がはりつめている", "category": "B", "reverse": False},
    {"id": "B11", "text": "B11. 不安だ", "category": "B", "reverse": False},
    {"id": "B12", "text": "B12. 落着かない", "category": "B", "reverse": False},
    {"id": "B13", "text": "B13. ゆううつだ", "category": "B", "reverse": False},
    {"id": "B14", "text": "B14. 何をするのも面倒だ", "category": "B", "reverse": False},
    {"id": "B15", "text": "B15. 物事に集中できない", "category": "B", "reverse": False},
    {"id": "B16", "text": "B16. 気が晴れない", "category": "B", "reverse": False},
    {"id": "B17", "text": "B17. 仕事が手につかない", "category": "B", "reverse": False},
    {"id": "B18", "text": "B18. 悲しいと感じる", "category": "B", "reverse": False},
    {"id": "B19", "text": "B19. めまいがする", "category": "B", "reverse": False},
    {"id": "B20", "text": "B20. 体のふしぶしが痛む", "category": "B", "reverse": False},
    {"id": "B21", "text": "B21. 頭が重かったり頭痛がする", "category": "B", "reverse": False},
    {"id": "B22", "text": "B22. 首筋や肩がこる", "category": "B", "reverse": False},
    {"id": "B23", "text": "B23. 腰が痛い", "category": "B", "reverse": False},
    {"id": "B24", "text": "B24. 目が疲れる", "category": "B", "reverse": False},
    {"id": "B25", "text": "B25. 動悸や息切れがする", "category": "B", "reverse": False},
    {"id": "B26", "text": "B26. 胃腸の具合が悪い", "category": "B", "reverse": False},
    {"id": "B27", "text": "B27. 食欲がない", "category": "B", "reverse": False},
    {"id": "B28", "text": "B28. 便秘や下痢をする", "category": "B", "reverse": False},
    {"id": "B29", "text": "B29. よく眠れない", "category": "B", "reverse": False},

    # C: 周囲のサポート (9問)
    {"id": "C1", "text": "C1. 上司にどのくらい気軽に話ができますか", "category": "C", "reverse": True},
    {"id": "C2", "text": "C2. 職場の同僚にどのくらい気軽に話ができますか", "category": "C", "reverse": True},
    {"id": "C3", "text": "C3. 配偶者、家族、友人にどのくらい気軽に話ができますか", "category": "C", "reverse": True},
    {"id": "C4", "text": "C4. 困った時、上司はどのくらい頼りになりますか", "category": "C", "reverse": True},
    {"id": "C5", "text": "C5. 困った時、職場の同僚はどのくらい頼りになりますか", "category": "C", "reverse": True},
    {"id": "C6", "text": "C6. 困った時、配偶者、家族、友人はどのくらい頼りになりますか", "category": "C", "reverse": True},
    {"id": "C7", "text": "C7. 個人的な問題を相談したら、上司はどのくらいきいてくれますか", "category": "C", "reverse": True},
    {"id": "C8", "text": "C8. 個人的な問題を相談したら、職場の同僚はどのくらいきいてくれますか", "category": "C", "reverse": True},
    {"id": "C9", "text": "C9. 個人的な問題を相談したら、配偶者、家族、友人はどのくらいきいてくれますか", "category": "C", "reverse": True},

    # D: 満足度 (2問)
    {"id": "D1", "text": "D1. 仕事に満足だ", "category": "D", "reverse": True},
    {"id": "D2", "text": "D2. 家庭生活に満足だ", "category": "D", "reverse": True},
]

scales = {
    "量的負担": ["A1", "A2", "A3"],
    "質的負担": ["A4", "A5", "A6", "A7"],
    "裁量権": ["A8", "A9", "A10"],
    "仕事の適性": ["A11", "A16"],
    "職場人間関係": ["A12", "A13", "A14"],
    "職場環境": ["A15"],
    "働きがい": ["A17"],
    "活気": ["B1", "B2", "B3"],
    "イライラ感": ["B4", "B5", "B6"],
    "疲労感": ["B7", "B8", "B9"],
    "不安感": ["B10", "B11", "B12"],
    "抑うつ感": ["B13", "B14", "B15", "B16", "B17", "B18"],
    "身体愁訴": ["B19", "B20", "B21", "B22", "B23", "B24", "B25", "B26", "B27", "B28", "B29"],
    "上司のサポート": ["C1", "C4", "C7"],
    "同僚のサポート": ["C2", "C5", "C8"],
    "家族・友人のサポート": ["C3", "C6", "C9"],
    "仕事満足度": ["D1"],
    "家庭満足度": ["D2"],
}
